name: Publish MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Mkdocs to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fix image embedding in notebooks
        run: python .github/workflows/utils/embed_images.py notebooks

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
            args: --verbose './**/*.md'
            fail: True
            
      - name: Rewrite notebook links for docs
        run: python .github/workflows/utils/rewrite_links.py notebooks
      - name: Copy notebooks into docs
        run: cp -r notebooks/* docs/ | echo "No notebooks found"
      - name: Deploy Mkdocs
        run: mkdocs gh-deploy --force
